services:
  website:
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
      - "3100:3100"
      - "4000:4000"
    command: nuxt dev
