services:
  dev:
    build:
      context: .
      dockerfile: Containerfile
      target: env
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app
    command: iles dev --host
